part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const REGISTRATION = _Paths.REGISTRATION;
  static const AUTH = _Paths.AUTH;
  static const OTP = _Paths.OTP;
  static const MAIN = _Paths.MAIN;
  static const HOME = _Paths.HOME;
  static const OTHER = _Paths.OTHER;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const SETTINGS = _Paths.SETTINGS;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const SUCCESS = _Paths.SUCCESS;
  static const FAILED = _Paths.FAILED;
  static const SUPPORT = _Paths.SUPPORT;
  static const SEND_SMS = _Paths.SEND_SMS;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const ABOUT = _Paths.ABOUT;
  static const TERMS = _Paths.TERMS;
  static const PRIVACY = _Paths.PRIVACY;
  static const CREATE_HOST_ACCOUNT = _Paths.CREATE_HOST_ACCOUNT;
  static const WELCOME_BACK = _Paths.WELCOME_BACK;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const PASSWORD_UPDATED = _Paths.PASSWORD_UPDATED;
  static const ADD_LISTING = _Paths.ADD_LISTING;
  static const TEAM_AND_STAFF = _Paths.TEAM_AND_STAFF;
  static const BOOKING_DETAILS = _Paths.BOOKING_DETAILS;
  static const FINANCIAL_OVERVIEW = _Paths.FINANCIAL_OVERVIEW;
  static const VERIFY_IDENTITY = _Paths.VERIFY_IDENTITY;
  static const HOST_CALENDAR = _Paths.HOST_CALENDAR;
  static const MY_PROPERTIES = _Paths.MY_PROPERTIES;
  static const SECURITY = _Paths.SECURITY;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const EXPENSE_ANALYSIS = _Paths.EXPENSE_ANALYSIS;
  static const ADD_NEW_BOOKING = _Paths.ADD_NEW_BOOKING;
  static const RECORD_PAYMENT = _Paths.RECORD_PAYMENT;
  static const LEGAL_DOCUMENTS = _Paths.LEGAL_DOCUMENTS;
  static const PROPERTY_VAULT = _Paths.PROPERTY_VAULT;
  static const DOCUMENT_SCANNER = _Paths.DOCUMENT_SCANNER;
  static const REFINE_SCAN = _Paths.REFINE_SCAN;
  static const SMART_ACCESS = _Paths.SMART_ACCESS;
  static const GUEST_ACCESS_CODES = _Paths.GUEST_ACCESS_CODES;
  static const MAINTENANCE_TASKS = _Paths.MAINTENANCE_TASKS;
  static const LISTING_PUBLISHED = _Paths.LISTING_PUBLISHED;
  static const STAFF_DETAIL = _Paths.STAFF_DETAIL;
  static const ENTRY_LOGS = _Paths.ENTRY_LOGS;
  static const ADD_EXPENSE = _Paths.ADD_EXPENSE;
}

abstract class _Paths {
  static const REGISTRATION = '/registration';
  static const AUTH = '/auth';
  static const OTP = '/otp';
  static const MAIN = '/main';
  static const HOME = '/home';
  static const OTHER = '/other';
  static const NOTIFICATIONS = '/notifications';
  static const SETTINGS = '/settings';
  static const SUCCESS = '/success';
  static const FAILED = '/failed';
  static const CHANGE_PASSWORD = '/change-password';
  static const SUPPORT = '/support';
  static const SEND_SMS = '/send-sms';
  static const SUBSCRIPTION = '/subscription';
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const ABOUT = '/about';
  static const TERMS = '/terms';
  static const PRIVACY = '/privacy';
  static const CREATE_HOST_ACCOUNT = '/create-host-account';
  static const WELCOME_BACK = '/welcome-back';
  static const RESET_PASSWORD = '/reset-password';
  static const PASSWORD_UPDATED = '/password-updated';
  static const ADD_LISTING = '/add-listing';
  static const TEAM_AND_STAFF = '/team-and-staff';
  static const BOOKING_DETAILS = '/booking-details';
  static const FINANCIAL_OVERVIEW = '/financial-overview';
  static const VERIFY_IDENTITY = '/verify-identity';
  static const HOST_CALENDAR = '/host-calendar';
  static const MY_PROPERTIES = '/my-properties';
  static const SECURITY = '/security';
  static const NEW_PASSWORD = '/new-password';
  static const EXPENSE_ANALYSIS = '/expense-analysis';
  static const ADD_NEW_BOOKING = '/add-new-booking';
  static const RECORD_PAYMENT = '/record-payment';
  static const LEGAL_DOCUMENTS = '/legal-documents';
  static const PROPERTY_VAULT = '/property-vault';
  static const DOCUMENT_SCANNER = '/document-scanner';
  static const REFINE_SCAN = '/refine-scan';
  static const SMART_ACCESS = '/smart-access';
  static const GUEST_ACCESS_CODES = '/guest-access-codes';
  static const MAINTENANCE_TASKS = '/maintenance-tasks';
  static const LISTING_PUBLISHED = '/listing-published';
  static const STAFF_DETAIL = '/staff-detail';
  static const ENTRY_LOGS = '/entry-logs';
  static const ADD_EXPENSE = '/add-expense';
}
